vilmibm/tildemush

client/tmclient/client.py

The current master crashes like this when you run the client:
> `Traceback (most recent call last):
>   File "/home/hvincent/repos/tildemush/venv/bin/tmclient", line 11, in <module>
>       load_entry_point('tildemush-client', 'console_scripts', 'tmclient')()
>   File "/home/hvincent/repos/tildemush/client/tmclient/__init__.py", line 8, in main
>       client.run()
>   File "/home/hvincent/repos/tildemush/client/tmclient/client.py", line 28, in run
>       self.loop.run()
> AttributeError: '_UnixSelectorEventLoop' object has no attribute 'run'`
This PR corrects the loop call in client.py so the client starts correctly.

fix client loop

---

client/tmclient/screens.py

this PR:
* implements the main game text as a listbox, which allows scrolling (closes #36)
future work:
* capture `pgup pgdn home end` keypresses to scroll through text
* make a scrollback cap, which users should be able to set manually for their client
question:
* i personally prefer if the initial text starts from the bottom and pushes upwards; currently, the initial text starts from the top and fills downwards. this is a pretty small cosmetic tweak, does either one way or the other make more sense? should this also be part of user-modifiable client settings? (i'm leaning towards 'make as many cosmetic tweaks adjustable by users as is practical', to be honest)

making main game text area scrollable

---

server/tmserver/live_test.py
server/tmserver/scripting.py
server/tmserver/tests/async_test.py
server/tmserver/tests/game_object_test.py
server/tmserver/witch_header.hy
server/tmserver/world.py

i donno maybe having someone's username is nice? so when you're reading out of context you are reminded of the author?
or is it just confusing noise?
either way it didn't mean anything; any nonsense could go in that spot...
Fixes #60

remove the "by user" part of witch macro

---

server/tmserver/models.py
server/tmserver/scripting.py
server/tmserver/tests/async_test.py
server/tmserver/tests/game_object_test.py
server/tmserver/world.py

The format I went with is slightly different than we discussed in IRC:
```python
{'exits': {
'north': {
'room_name': 'Replicator Room',
'exit_name': 'Sliding Door'
}, 
'below': {
'room_name': 'Jeffries Tube',
'exit_name': 'Small Hatch',}}}
```
If no exit exists for a given direction, it's not in `exits`. We've talked about only using `room_name` in the minimap, but I figured `exit_name` might come in handy eventually.
Fixes #68

List exits

---

server/tmserver/models.py
server/tmserver/tests/async_test.py
server/tmserver/tests/game_object_test.py
server/tmserver/tests/inventory_test.py
server/tmserver/util.py
server/tmserver/world.py

fixes #67 
this PR:
- adds `get`, `drop`, `put`, `remove` commands
- adds at least one async test for each
- adds full unit tests for each
- introduces `util` module with code for stripping color codes / collapsing whitespace
- makes fuzzy matching ignore color codes

Inventory commands

---

client/tmclient/screens.py

this pr:
* fixes #92 by adding a padding line to main game area
* implements #74 (currently defaulting to `shift up` etc., which is an arbitrary meta key i picked that doesn't collide with my personal computing environment; this should be overrideable by user settings eventually)
* polishes a minor display issue with the minimap
* adding command history scrolling (via #89)

UI updates

---

server/tmserver/core.py
server/tmserver/errors.py
server/tmserver/migrations.py
server/tmserver/models.py
server/tmserver/scripting.py
server/tmserver/tests/async_test.py
server/tmserver/tests/contain_test.py
server/tmserver/tests/game_object_test.py
server/tmserver/tests/inventory_test.py
server/tmserver/tests/move_test.py
server/tmserver/tests/perm_test.py
server/tmserver/tests/revision_test.py
server/tmserver/world.py

This PR adds a new payload handler called `REVISION`.
Part of #82 
It:
- takes a new pile of WITCH for an object
- saves a new revision
- reports on compilation errors
- lets gameobjects in RAM notice these new revisions lazily and try to use them, only upgrading themselves if the WITCH compiles ok
- eventually responds to any REVISION payload with an OBJECT payload
TODO:

Implement REVISION handling on server

---

server/tmserver/core.py
server/tmserver/models.py
server/tmserver/tests/async_test.py
server/tmserver/world.py

Part of #82 
This completes the first round of implementation for the /edit command as far as the server is concerned; we still need to get it hooked up to the client.
This PR:
- Accepts `/edit shortname`
- Locks/unlocks objects accordingly in a new table
- Sends the initial OBJECT payload to the client

/edit handler

---

client/tmclient/screens.py
client/tmclient/ui.py

this PR:
* stubs out a bunch of WITCH panel elements (closes #77 and item 3 in #13)
* performs scope checking for objects being targeted for `/edit`
minor ui tweaks unrelated to WITCH:
* switches the position of above/below rooms in the minimap
* adds text coloration to player speech for game area legibility
* corrects a small error in room content display that wasn't showing all objects

witch panel updates

---

README.md
a_little_postgres.md
server/tmserver/config.py

Here's some changes that describe how to set up the PostgreSQL database without needing sudo or mucking around with unix ports
But after actually writing it it looks more complex than I thought it would. Maybe it would be too overwhelming for a novice?
Also I just noticed that it's not good to keep `pgdata` in the project directory if the project directory is the git clone. That would probably cease to be an issue if we add `pgdata` to the `.gitignore`.
If this isn't useful, no worries! I wanted to write up the thing about "a little postgres" anyway; I can publish it elsewhere :smile:

how to set up postgres without sudo

---

client/tmclient/client.py
client/tmclient/config.py
client/tmclient/screens.py
client/tmclient/ui.py

this PR makes a pass on client ui/screens classes, cleaning up the code for tab handlers to make it easier to add new features and tweak existing ones.
changes:
* moves all game tab stuff (including gameprompt) into their own classes in ui.py
* adds a scope handler to the WITCH tab, which displays a list of object names in scope (okay i guess this is a little more than just a refactor but i was on a roll)
* preps for settings pane stuff by introducing user config (includes ability to customize mini panel layout in the game tab)

client tab refactor

---

client/tmclient/ui.py

this PR fixes the reset color code in the client, which will go beyond just correcting the `say` output; now all text that uses `/` or `reset` will return to the default terminal color, instead of white.

closes #125 by fixing reset color code

---

client/tmclient/ui.py

this PR addresses #133 by just hardcoding `nano` as the default editor if the user does not have the `$EDITOR` environment variable set. on a future pass, this could be less hardcoded, but for the moment, this will at least keep the client from crashing in this instance.

editor patch

---

server/setup.py
server/tmserver/scripting.py
server/tmserver/tests/evil_witch_test.py
server/tmserver/tests/game_object_test.py
server/tmserver/tests/mode_test.py
server/tmserver/witch_header.hy

this PR covers using `asteval` to run compiled Hy code. It prevents module import and leaky object introspection. This PR also fixes up the main `witch` macro so it hides references to DB models and ScriptEngines.

Sandbox spike

---

run-a-little-postgres.sh

`run-a-little-postgres.sh` is no longer as hep.

Fix a typo

---

server/tmserver/models.py
server/tmserver/scripting.py
server/tmserver/tests/async_test.py
server/tmserver/tests/evil_witch_test.py
server/tmserver/tests/game_object_test.py
server/tmserver/tests/revision_test.py
server/tmserver/world.py

This PR augments WITCH scripts being pulled up for editing with a `(has ...)` section that reflects an object's key value data and updates that key value data when saving a script.
This means that updating things like `name` and `description` actually have a meaningful effect (though you might have to drop/pick up the edited item before the UI reflects a name change...)
The one caveat to this PR is that when `(has ...)` is written back out, it runs the whole map together on one line. I couldn't think of a great, easy way to fix this so I'm leaving it alone for now.
This PR also includes a check in the call to `(set-data k v)` that avoids messing with the object's data if it's currently being edited.

WITCH scripts represent live state of database

---

server/tmserver/tests/async_test.py
server/tmserver/tests/contain_test.py
server/tmserver/world.py

ugh async test is getting even unwieldier with more STATEs (not to mentioned existing COMMAND OKs). I'm thinking seriously about filtering those out in tests by default then having a few test cases that just make sure STATE is sent when appropriate.

Improve state send

---

client/tmclient/screens.py
client/tmclient/ui.py
server/tmserver/core.py

Fixes #177 
This works!
There is *NO CACHING* or any optimizations at all for this and it will be one of the first things to hurt tush's performance i think, but we'll cross that bridge when we come to it.
@modgethanc can you think of a better way to do "take arbitrary action when tab is shown"? i don't like what i did (sniffing for map tab and doing something conditionally), but when i put a call back on the map tab realized i didn't have access to the async client...

show map in client

---

client/tmclient/client.py
server/tmserver/core.py
server/tmserver/world.py

we were lazily starting up a listen loop after a user's first attempt at input; this PR unlazily starts the loop after a successful login and issues a new `REFRESH` command that triggers a send of client state.

fix needing initial manual /look

---

README.md
client/setup.py

The `--process-dependency-links` option was removed [in pip v19](https://pip.pypa.io/en/stable/news/#id19). So, let's grab the tarball directly using the GitHub API so we can continue to use new versions of pip.

Don't use --process-dependency-links for client setup
