vilmibm/tildemush

- client/tmclient/screens.py
- server/tmserver/core.py
- server/tmserver/migrations.py
- server/tmserver/tests/async_test.py
- server/tmserver/world.py
> Look command

- server/tmserver/core.py
- server/tmserver/models.py
- server/tmserver/tests/async_test.py
- server/tmserver/world.py
the relevant test is currently failing and i'm pausing for the night but here's the on-containership-change world state implementation. Fixes #48
> [wip] World state

- server/tmserver/models.py
- server/tmserver/scripting.py
- server/tmserver/tests/game_object_test.py
- server/tmserver/world.py
> Some cleanup

- client/tmclient/screens.py
this PR:
* handles STATE data from the server
* updates here panel with current `/look` information, taken from STATE (closes #41, completes last item of #13)
* updates player info panel with STATE (completes second to last item of #13)
a small issue:
the initial STATE push from the server doesn't get received by the client until after the client sends something after login; i'm not sure how the asyncio stuff works here, so i don't know how to address this. ideally, that STATE info would come in and update all the info panels without the user having to send a command.
> client STATE updates

- client/tmclient/screens.py
this PR:
* adds manual scrolling for the main game area text (closes #51); i'm not totally happy with the scrolling behavior but it's good enough for now
* corrects inventory display in the user panel
* adds a `/quit` command that can be entered in the main prompt; this still doesn't really do anything special besides kill the client
> small client polish

- client/tmclient/screens.py
- client/tmclient/ui.py
ui.ColorText extends urwid.Text, turns handlebar color codes in the string into urwid markup.  Standard colors have named palletes.
> ui.ColorText, inline color templating for the client

- server/tmserver/models.py
- server/tmserver/tests/perm_test.py
> add Permission model

- server/tmserver/tests/async_test.py
- server/tmserver/world.py
> respect world-writable perm when making exits

- server/tmserver/tests/move_test.py
- server/tmserver/world.py
adds movement aliases (closes #97), and tests for movement.
> Direction aliases

- client/tmclient/screens.py
- server/tmserver/core.py
- server/tmserver/errors.py
- server/tmserver/models.py
- server/tmserver/tests/async_test.py
- server/tmserver/world.py
> clean {dis,re}connect

- client/tmclient/screens.py
fixes game area scrolling that was broken in the most recent client refactor.
> patching game area scrolling

- .gitignore
- client/tmclient/screens.py
- run-a-little-postgres.sh
a helper script to get a little postgres running, plus a fix for a typo in the client
> make local dev work on macos more easily

- client/tmclient/tests/ui_test.py
This adds initial client test. Specifically, it tests that colors are parsed as they should be.
Your critical peer reviews are encouraged, as I am a novice.
> Add initial client UI tests

- server/tmserver/config.py
- server/tmserver/models.py
- server/tmserver/scripting.py
- server/tmserver/tests/async_test.py
- server/tmserver/tests/evil_witch_test.py
- server/tmserver/tests/game_object_test.py
- server/tmserver/tests/revision_test.py
- server/tmserver/witch_header.hy
- server/tmserver/world.py
This PR covers the first pass on the new `(incantation)` macro, the version of WITCH that is intended for beta release.
Fixes #165 
Fixes #143 
Fixes #78 
Fixes #152 
Fixes #164
> WITCH reimplementation, first pass

- server/tmserver/migrations.py
- server/tmserver/tests/contain_test.py
> clear out orphaned player objs on server start

- client/tmclient/ui.py
> Fix issue with no EDITOR set, change default to /bin/nano

- client/tmclient/screens.py
- client/tmclient/ui.py
- server/tmserver/core.py
- server/tmserver/logs.py
- server/tmserver/mapping.py
- server/tmserver/models.py
- server/tmserver/scripting.py
- server/tmserver/witch_header.hy
- server/tmserver/world.py
i tried to:
- delete obsolete TODOs
- delete TODOs very well captured by issues
- mark TODOs helpful in resolving an issue with the issue they are related to
and ignored TODOs in witch_header (too in flux) and in tests (just too much to think about rn)
> Todo audit

- server/tmserver/scripting.py
- server/tmserver/tests/async_test.py
- server/tmserver/witch_header.hy
it's mainly copypasta of (hears). test had to be slightly different for
unknown reasons.
Fixes #189
> add (sees) macro

- server/tmserver/scripting.py
- server/tmserver/tests/async_test.py
- server/tmserver/tests/game_object_test.py
the tests are kind of goofy but eh
Fixes #144
> add (random-number)

- client/tmclient/screens.py
- client/tmclient/ui.py
- server/tmserver/tests/async_test.py
- server/tmserver/world.py
rudimentary /read command
Fixes #148 
You have to manually go back to the main game screen with F1.
> Read command

- README.md
- client/tmclient/config.py
limiting this to just the permission from https://github.com/vilmibm/tildemush/issues/35
> chmod 600 user config
